export interface IUrl {
    _id?: string,
    proyect?: string,
    company?: string,
    url: string,
    platform?: string,
    ipExternal?: string,
    roundValidation?: string,
    platformManager?: string,
    lastRevisionDate: string,
    avCritical?: number,
    avHigh?: number,
    avMedium?: number,
    avLow?: number,
    ptCritical?: number,
    ptHigh?: number,
    ptMedium?:number,
    ptLow?: number,
    QtrimestreExecuted?: string,
    yearExecuted?: string,
    qualification?: string;
    avOpen?: string,
    ptOpen?: string,
    currentRound?: string,
    avMitigatedCriticism?: number,
    avMitigatedHigh?: number,
    avMitigatedMedium?: number,
    avMitigatedLow?: number,
    ptMitigatedCriticism?: number,
    ptMitigatedHigh?: number,
    ptMitigatedMedium?: number,
    ptMitigatedLow?: number,
    date?: string,
    executedBy?: string,
    history?: Array<IUrl>
}