export interface IUrl {
    _id?: string,
    proyecto?: string,
    empresa?: string,
    url: string,
    plataforma?: string,
    ipExterna?: string,
    rondaValidacion?: string,
    responsablePlataforma?: string,
    fechaUltimaRevision: string,
    avCriticas?: number,
    avAltas?: number,
    avMedias?: number,
    avBajas?: number,
    ptCriticas?: number,
    ptAltas?: number,
    ptMedias?:number,
    ptBajas?: number,
    QtrimestreEjecutado?: string,
    anoEjecutado?: string,
    calificacion?: string;
    avOpen?: string,
    ptOpen?: string,
    rondaActual?: string,
    avCriticasMitigadas?: number,
    avAltasMitigadas?: number,
    avMediasMitigadas?: number,
    avBajasMitigadas?: number,
    ptCriticasMitigadas?: number,
    ptAltasMitigadas?: number,
    ptMediasMitigadas?: number,
    ptBajasMitigadas?: number,
    fecha?: string,
    ejecutadoPor?: string,
    historial?: Array<IUrl>
}